FLAGS = -Wall -Werror -Wextra -Wno-unused

.PHONY: all fclean

all:
	@bash ./menu.sh

poly:
	c++ ${FLAGS} poly11.cpp

polyVir:
	c++ ${FLAGS} poly12.cpp

poly2:
	c++ ${FLAGS} poly2.cpp

fclean:
	rm -f ./a.out
